apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-client
spec:
  selector:
    matchLabels:
      app: vllm-client
  template:
    metadata:
      labels:
        app: vllm-client
    spec:
      containers:
      - name: gradio
        image: us-docker.pkg.dev/google-samples/containers/gke/gradio:v0.0.6
        env:
          - name: LLM_URL
            value: "http://llm-service"
          - name: LLM_NAME
            value: "meta-llama/Llama-2-7b-hf"
          - name: MAX_TOKENS
            value: "400"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-client-service
spec:
  type: LoadBalancer
  selector:
    app: gradio
  ports:
  - port: 8080
    targetPort: 7860