steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build Image
  entrypoint: bash
  args:
    - -c
    - |
      docker build . -t us-east1-docker.pkg.dev/rick-vertex-ai/gke-llm/vllm:latest  \
      && docker push us-east1-docker.pkg.dev/rick-vertex-ai/gke-llm/vllm:latest 
 
images:
- 'us-east1-docker.pkg.dev/rick-vertex-ai/gke-llm/vllm:latest'